spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/library_users_db
spring.datasource.username=library_admin
spring.datasource.password=UserService123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.google.provider=google

jwt.secret=${JWT_SECRET}

service.notifications.url=http://notification-service:8080

