spring.application.name=smart-library-ai


spring.datasource.url=jdbc:postgresql://localhost:5432/smart_library_db
spring.datasource.username=library_user
spring.datasource.password=library_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


groq.api.url=https://api.groq.com/openai/v1

groq.api.key=${GROQ_API_KEY}
groq.model=openai/gpt-oss-20b
server.port=9090

service.books.url=http://book-service:8080
service.users.url=http://user-service:9000
service.loans.url=http://book-service:8080